### ISSUE TITLE
Add support for an ISO 8601 timezone compliant token expiration date-timestamp

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-sdk#171]
## Description

In order to support the server adding timezone information to the token expiration timestamp, the SDK needs to update https://github.com/freedomofpress/securedrop-sdk/blob/9b70550f1dc43a052f5025265473281e05c738a1/sdclientapi/__init__.py#L251 to allow timezone data.

For background info, see https://github.com/freedomofpress/securedrop/pull/6256. If the Journalist API begins sending timezone info without any update to the SDK, the following issue will occur when you start the `securedrop-client`:

![check_everything_ohno](https://user-images.githubusercontent.com/22777700/153079467-391ab4f1-00ee-4043-8843-fc77522ac99e.png)

And the error log:

```
2022-02-08 16:21:31,201 - root:206(start_app) INFO: Starting SecureDrop Client 0.6.0-rc2
2022-02-08 16:22:11,743 - securedrop_client.logic:126(call_api) ERROR: time data '2022-02-09T05:22:12.165773+00:00Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

**Comment by gonzalo-bulnes** [comment]
I have reasons to think that it is preferable that we favor writing the UTC offset as `+00:00` instead of `Z`. I've written the details in https://github.com/freedomofpress/securedrop/issues/6257

For clarity: I don't think this is exclusif of supporting the `Z` notation. Part of the plan laid out in that issue includes making sure the SDK is lenient in its inputs, so I would still support the `Z` notation for the time being.
