### ISSUE TITLE
`test-against-latest-api` server test errors out

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-sdk#183]
As observed in #182:
[test output](https://app.circleci.com/jobs/github/freedomofpress/securedrop-sdk/2428) - "Connection reset by peer" errors

**Comment by eloquence** [comment]
What this test is for: to test the SDK against the latest version of the API, flagging any breakage. I think it's worth keeping along with the SDK, while we have it.

Why it's failing:

My read on the output is that `make dev` now takes a bit longer from the time the ports are exposed to the API responding to requests, due to the additional installation of the Rust environment. This causes the test to run before the server is fully ready. Use of `sleep`, as almost always, makes for brittle code.

We can "fix" it by making it sleep for longer (CI passes on 452ac32d1c7bcc9001ebf2c63cd21e19af6c86c8), but that does nothing about the underlying brittleness. Alternatively, we could re-arrange the order in `make dev`, or there might be another option I'm missing to determine server readiness.

**Comment by legoktm** [comment]
In theory the `dockerize -wait` command should wait until the flask apps are running so no sleep is needed, but I'm guessing it thinks once the container starts and it can connect to the port, it is "up" and then the sleep is really what's waiting for the apps to start.

It would be better if we had a wait command that paused until the apps are up and found e.g. "Powered by" before exiting. I think we could do that in a 5-10 line Python script instead of using dockerize.

**Comment by legoktm** [comment]
> but I'm guessing it thinks once the container starts and it can connect to the port, it is "up" and then the sleep is really what's waiting for the apps to start.

In fact, we had told dockerize to be happy with a tcp port instead of getting a good HTTP response. If we switch the protocol in the command to "http" then it waits until it gets a 2XX status code (see https://github.com/jwilder/dockerize/blob/master/main.go#L143) before exiting.
